using UnityEngine;
using System.Collections.Generic;
using System.Linq;
using Sirenix.OdinInspector;

[System.Serializable]
public struct HexCoordinates
{
    public int q; // Column
    public int r; // Row
    
    public HexCoordinates(int q, int r)
    {
        this.q = q;
        this.r = r;
    }
    
    public static HexCoordinates Zero => new HexCoordinates(0, 0);
    
    public override string ToString() => $"({q}, {r})";
    
    public override bool Equals(object obj)
    {
        if (obj is HexCoordinates other)
            return q == other.q && r == other.r;
        return false;
    }
    
    public override int GetHashCode()
    {
        return q.GetHashCode() ^ (r.GetHashCode() << 2);
    }
    
    public static bool operator ==(HexCoordinates a, HexCoordinates b)
    {
        return a.q == b.q && a.r == b.r;
    }
    
    public static bool operator !=(HexCoordinates a, HexCoordinates b)
    {
        return !(a == b);
    }
}

public enum HexType
{
    [LabelText("🌿 Environment (Decorative)")]
    Environment,
    
    [LabelText("🏠 Center Hub")]
    CenterHub,
    
    [LabelText("🛤️ Pathway (Enemy Route)")]
    Pathway,
    
    [LabelText("🛡️ Defender Spot")]
    DefenderSpot,
    
    [LabelText("🚪 Edge Spawn")]
    EdgeSpawn
}

[System.Serializable]
public class HexData
{
    public HexCoordinates coordinates;
    public HexType type;
    public GameObject gameObject;
    public int laneId = -1; // Which lane this hex belongs to (-1 = no lane)
    public bool isJunctionPoint = false; // Where lanes merge
    
    public HexData(HexCoordinates coords, HexType hexType)
    {
        coordinates = coords;
        type = hexType;
    }
}

[System.Serializable]
public class LaneConfiguration
{
    [LabelText("Lane Active")]
    public bool isActive = true;
    
    [LabelText("Target Direction"), Range(0f, 360f)]
    public float direction = 0f; // Degrees from center
    
    [LabelText("Lane Length"), Range(2, 15)]
    public int length = 5;
    
    [LabelText("Merge with Lane")]
    public int mergeWithLane = -1; // -1 = no merge, otherwise lane index
    
    [LabelText("Merge at Distance"), Range(1, 10)]
    public int mergeAtDistance = 3; // How far from center to merge
    
    [LabelText("Lane Color")]
    public Color laneColor = Color.yellow;
}

public class HexEnvironmentManager : MonoBehaviour
{
    [TitleGroup("Grid Settings")]
    [SerializeField, Range(1, 20), Tooltip("Number of hex rings around the center hex")]
    private int gridRadius = 5;
    
    [TitleGroup("Grid Settings")]
    [SerializeField, Range(0.1f, 10f), Tooltip("Size of each hexagon")]
    private float hexSize = 1f;
    
    [TitleGroup("Grid Settings")]
    [SerializeField, Range(0f, 0.5f), Tooltip("Gap between hexagons (0 = touching)")]
    private float hexSpacing = 0.05f;
    
    [TitleGroup("Tower Defense Settings")]
    [SerializeField, Range(1, 6), Tooltip("Number of lanes to generate")]
    private int numberOfLanes = 3;
    
    [TitleGroup("Tower Defense Settings")]
    [SerializeField, Tooltip("Seed for deterministic generation (0 = random)")]
    private int generationSeed = 0;
    
    [TitleGroup("Tower Defense Settings")]
    [SerializeField, Tooltip("Configuration for each lane")]
    [ListDrawerSettings(ShowIndexLabels = true, DraggableItems = false)]
    private List<LaneConfiguration> laneConfigurations = new List<LaneConfiguration>();
    
    [TitleGroup("Tower Defense Settings")]
    [SerializeField, Tooltip("Automatically generate defender spots adjacent to pathways")]
    private bool autoGenerateDefenderSpots = true;
    
    [TitleGroup("Tower Defense Settings")]
    [SerializeField, Tooltip("Mark edge hexagons as spawn points")]
    private bool markEdgeAsSpawn = true;
    
    [TitleGroup("Prefab Settings")]
    [SerializeField, Required, Tooltip("Default hexagon prefab")]
    private GameObject hexPrefab;
    
    [TitleGroup("Prefab Settings")]
    [SerializeField, Tooltip("Center hub prefab (optional)")]
    private GameObject centerHubPrefab;
    
    [TitleGroup("Prefab Settings")]
    [SerializeField, Tooltip("Pathway prefab (optional)")]
    private GameObject pathwayPrefab;
    
    [TitleGroup("Prefab Settings")]
    [SerializeField, Tooltip("Defender spot prefab (optional)")]
    private GameObject defenderSpotPrefab;
    
    [TitleGroup("Prefab Settings")]
    [SerializeField, Tooltip("Edge spawn prefab (optional)")]
    private GameObject edgeSpawnPrefab;
    
    [TitleGroup("Prefab Settings")]
    [SerializeField, Tooltip("Optional parent transform for spawned hexagons")]
    private Transform hexParent;
    
    [TitleGroup("Generation")]
    [SerializeField, Tooltip("Generate environment automatically on Start")]
    private bool generateOnStart = true;
    
    [TitleGroup("Debug")]
    [SerializeField, Tooltip("Show gizmos for hex positions")]
    private bool showGizmos = true;
    
    [TitleGroup("Debug")]
    [SerializeField, Tooltip("Show hex type labels in scene view")]
    private bool showTypeLabels = true;
    
    [TitleGroup("Debug")]
    [SerializeField, Tooltip("Show filled gizmos instead of wireframe")]
    private bool showFilledGizmos = false;
    
    [TitleGroup("Debug")]
    [SerializeField, Tooltip("Show lane connections between hexes")]
    private bool showLaneConnections = true;
    
    [TitleGroup("Debug")]
    [SerializeField, Tooltip("Gizmo transparency"), Range(0.1f, 1f)]
    private float gizmoAlpha = 0.7f;
    
    [TitleGroup("Debug - Hex Type Visibility")]
    [SerializeField, Tooltip("Show center hub hexes")]
    private bool showCenterHub = true;
    
    [TitleGroup("Debug - Hex Type Visibility")]
    [SerializeField, Tooltip("Show pathway hexes")]
    private bool showPathways = true;
    
    [TitleGroup("Debug - Hex Type Visibility")]
    [SerializeField, Tooltip("Show defender spot hexes")]
    private bool showDefenderSpots = true;
    
    [TitleGroup("Debug - Hex Type Visibility")]
    [SerializeField, Tooltip("Show edge spawn hexes")]
    private bool showEdgeSpawns = true;
    
    [TitleGroup("Debug - Hex Type Visibility")]
    [SerializeField, Tooltip("Show environment hexes")]
    private bool showEnvironment = false;
    
    [TitleGroup("Debug - Hex Colors")]
    [SerializeField, Tooltip("Color for center hub")]
    private Color centerHubColor = new Color(0.2f, 1f, 0.2f, 1f);
    
    [TitleGroup("Debug - Hex Colors")]
    [SerializeField, Tooltip("Color for defender spots")]
    private Color defenderSpotColor = new Color(1f, 0.3f, 0.3f, 1f);
    
    [TitleGroup("Debug - Hex Colors")]
    [SerializeField, Tooltip("Color for edge spawn points")]
    private Color edgeSpawnColor = new Color(0.3f, 0.6f, 1f, 1f);
    
    [TitleGroup("Debug - Hex Colors")]
    [SerializeField, Tooltip("Color for environment hexes")]
    private Color environmentColor = new Color(0.7f, 0.7f, 0.7f, 1f);
    
    [TitleGroup("Debug - Advanced")]
    [SerializeField, Tooltip("Show hex coordinates")]
    private bool showCoordinates = false;
    
    [TitleGroup("Debug - Advanced")]
    [SerializeField, Tooltip("Show only specific lane (0-5, -1 = all)"), Range(-1, 5)]
    private int showOnlyLane = -1;
    
    // Runtime data
    private Dictionary<HexCoordinates, HexData> hexGrid = new Dictionary<HexCoordinates, HexData>();
    private List<HexCoordinates> generatedCoordinates = new List<HexCoordinates>();
    private List<List<HexCoordinates>> generatedLanes = new List<List<HexCoordinates>>();
    
    // Hex math constants
    private readonly float SQRT_3 = Mathf.Sqrt(3f);
    
    // Hex direction vectors (for pathfinding)
    private readonly HexCoordinates[] HEX_DIRECTIONS = {
        new HexCoordinates(1, 0),   // E
        new HexCoordinates(0, 1),   // NE
        new HexCoordinates(-1, 1),  // NW
        new HexCoordinates(-1, 0),  // W
        new HexCoordinates(0, -1),  // SW
        new HexCoordinates(1, -1)   // SE
    };
    
    #region Unity Events
    
    private void Start()
    {
        InitializeLaneConfigurations();
        
        if (generateOnStart)
        {
            GenerateTowerDefenseEnvironment();
        }
    }
    
    private void OnValidate()
    {
        InitializeLaneConfigurations();
    }
    
    #endregion
    
    #region Initialization
    
    private void InitializeLaneConfigurations()
    {
        // Ensure we have the right number of lane configurations
        while (laneConfigurations.Count < numberOfLanes)
        {
            float direction = (360f / numberOfLanes) * laneConfigurations.Count;
            laneConfigurations.Add(new LaneConfiguration
            {
                direction = direction,
                laneColor = Color.HSVToRGB((float)laneConfigurations.Count / numberOfLanes, 0.8f, 1f)
            });
        }
        
        // Remove excess configurations
        if (laneConfigurations.Count > numberOfLanes)
        {
            laneConfigurations.RemoveRange(numberOfLanes, laneConfigurations.Count - numberOfLanes);
        }
    }
    
    #endregion
    
    #region Public Methods
    
    [TitleGroup("Generation")]
    [Button(ButtonSizes.Large, Name = "Generate Tower Defense Environment", Icon = SdfIconType.Shield)]
    [GUIColor(0.4f, 0.8f, 0.4f)]
    public void GenerateTowerDefenseEnvironment()
    {
        ClearExistingHexes();
        InitializeLaneConfigurations();
        
        // Initialize random seed
        if (generationSeed == 0)
        {
            generationSeed = Random.Range(1, int.MaxValue);
        }
        Random.InitState(generationSeed);
        
        if (hexPrefab == null)
        {
            Debug.LogError($"[HexEnvironmentManager] Hex prefab is not assigned!");
            return;
        }
        
        // Setup parent if not assigned
        if (hexParent == null)
        {
            GameObject parentGO = new GameObject("Tower Defense Grid");
            parentGO.transform.SetParent(transform);
            hexParent = parentGO.transform;
        }
        
        // Step 1: Generate all hex coordinates
        GenerateAllHexCoordinates();
        
        // Step 2: Generate lanes from center outwards
        GenerateLanes();
        
        // Step 3: Generate defender spots adjacent to pathways
        if (autoGenerateDefenderSpots)
            GenerateDefenderSpots();
            
        // Step 4: Mark edge hexes as spawn points
        if (markEdgeAsSpawn)
            MarkEdgeSpawns();
            
        // Step 5: Instantiate GameObjects
        InstantiateHexGameObjects();
        
        Debug.Log($"[HexEnvironmentManager] Generated tower defense environment with {hexGrid.Count} hexagons, {generatedLanes.Count} lanes (Seed: {generationSeed})");
    }
    
    [TitleGroup("Generation")]
    [Button(ButtonSizes.Medium, Name = "Randomize Seed", Icon = SdfIconType.Shuffle)]
    [GUIColor(0.8f, 0.8f, 0.4f)]
    public void RandomizeSeed()
    {
        generationSeed = Random.Range(1, int.MaxValue);
        Debug.Log($"[HexEnvironmentManager] New seed: {generationSeed}");
    }
    
    [TitleGroup("Generation")]
    [Button(ButtonSizes.Medium, Name = "Clear Environment", Icon = SdfIconType.Trash)]
    [GUIColor(0.8f, 0.4f, 0.4f)]
    public void ClearExistingHexes()
    {
        // Clear runtime collections
        hexGrid.Clear();
        generatedCoordinates.Clear();
        generatedLanes.Clear();
        
        // Destroy existing hex objects
        if (hexParent != null)
        {
            for (int i = hexParent.childCount - 1; i >= 0; i--)
            {
                if (Application.isPlaying)
                    Destroy(hexParent.GetChild(i).gameObject);
                else
                    DestroyImmediate(hexParent.GetChild(i).gameObject);
            }
        }
    }
    
    public HexData GetHexAt(HexCoordinates coord)
    {
        hexGrid.TryGetValue(coord, out HexData hex);
        return hex;
    }
    
    public GameObject GetHexGameObjectAt(HexCoordinates coord)
    {
        var hexData = GetHexAt(coord);
        return hexData?.gameObject;
    }
    
    public List<HexData> GetHexesOfType(HexType type)
    {
        return hexGrid.Values.Where(hex => hex.type == type).ToList();
    }
    
    public List<HexData> GetLaneHexes(int laneId)
    {
        return hexGrid.Values.Where(hex => hex.laneId == laneId).ToList();
    }
    
    public HexCoordinates WorldToHex(Vector3 worldPosition)
    {
        Vector3 localPos = worldPosition - transform.position;
        float size = hexSize * (1f + hexSpacing);
        
        // Convert world position to axial coordinates (flat-top orientation)
        float q = (2f/3f * localPos.x) / size;
        float r = (-1f/3f * localPos.x + SQRT_3/3f * localPos.z) / size;
        
        return CubeToHex(CubeRound(q, -q-r, r));
    }
    
    #endregion
    
    #region Tower Defense Generation
    
    private void GenerateAllHexCoordinates()
    {
        // Generate all hex coordinates in rings from center outwards
        for (int ring = 0; ring <= gridRadius; ring++)
        {
            List<HexCoordinates> ringCoords = GetHexRing(HexCoordinates.Zero, ring);
            
            foreach (var coord in ringCoords)
            {
                // Start as environment, will be changed by lane generation
                HexType type = ring == 0 ? HexType.CenterHub : HexType.Environment;
                HexData hexData = new HexData(coord, type);
                
                hexGrid[coord] = hexData;
                generatedCoordinates.Add(coord);
            }
        }
    }
    
    private void GenerateLanes()
    {
        generatedLanes.Clear();
        
        for (int laneIndex = 0; laneIndex < numberOfLanes; laneIndex++)
        {
            if (!laneConfigurations[laneIndex].isActive) continue;
            
            var config = laneConfigurations[laneIndex];
            List<HexCoordinates> laneCoords = new List<HexCoordinates>();
            
            // Calculate direction vector with some randomness based on seed
            float baseDirection = config.direction;
            float directionVariance = Random.Range(-10f, 10f); // Add some randomness
            float radians = (baseDirection + directionVariance) * Mathf.Deg2Rad;
            Vector3 direction = new Vector3(Mathf.Cos(radians), 0, Mathf.Sin(radians));
            
            // Generate lane path from center outwards
            HexCoordinates currentHex = HexCoordinates.Zero;
            laneCoords.Add(currentHex);
            
            for (int distance = 1; distance <= config.length; distance++)
            {
                // Find the hex closest to our desired direction
                HexCoordinates nextHex = FindClosestHexInDirection(currentHex, direction);
                
                // Add some randomness to path selection
                if (Random.value < 0.3f && distance > 1) // 30% chance for alternative path
                {
                    var alternatives = GetAlternativeDirections(currentHex, direction);
                    if (alternatives.Count > 0)
                    {
                        nextHex = alternatives[Random.Range(0, alternatives.Count)];
                    }
                }
                
                // Check for lane merging
                if (config.mergeWithLane >= 0 && distance >= config.mergeAtDistance && 
                    config.mergeWithLane < generatedLanes.Count)
                {
                    // Try to merge with existing lane
                    var targetLane = generatedLanes[config.mergeWithLane];
                    if (distance - config.mergeAtDistance < targetLane.Count)
                    {
                        nextHex = targetLane[distance - config.mergeAtDistance];
                    }
                }
                
                if (hexGrid.ContainsKey(nextHex))
                {
                    laneCoords.Add(nextHex);
                    currentHex = nextHex;
                }
                else
                {
                    break; // Reached edge of grid
                }
            }
            
            // Apply lane to hex data
            foreach (var coord in laneCoords)
            {
                if (hexGrid.ContainsKey(coord))
                {
                    hexGrid[coord].type = coord == HexCoordinates.Zero ? HexType.CenterHub : HexType.Pathway;
                    hexGrid[coord].laneId = laneIndex;
                }
            }
            
            generatedLanes.Add(laneCoords);
        }
    }
    
    private void GenerateDefenderSpots()
    {
        var pathwayHexes = hexGrid.Values.Where(hex => hex.type == HexType.Pathway).ToList();
        
        foreach (var pathwayHex in pathwayHexes)
        {
            // Check all 6 adjacent hexes
            foreach (var direction in HEX_DIRECTIONS)
            {
                HexCoordinates adjacentCoord = new HexCoordinates(
                    pathwayHex.coordinates.q + direction.q,
                    pathwayHex.coordinates.r + direction.r
                );
                
                if (hexGrid.ContainsKey(adjacentCoord) && 
                    hexGrid[adjacentCoord].type == HexType.Environment)
                {
                    hexGrid[adjacentCoord].type = HexType.DefenderSpot;
                }
            }
        }
    }
    
    private void MarkEdgeSpawns()
    {
        foreach (var kvp in hexGrid)
        {
            var coord = kvp.Key;
            var hexData = kvp.Value;
            
            // Check if this hex is on the outer edge
            int distance = Mathf.Max(Mathf.Abs(coord.q), Mathf.Abs(coord.r), Mathf.Abs(-coord.q - coord.r));
            
            if (distance == gridRadius && hexData.type == HexType.Environment)
            {
                hexData.type = HexType.EdgeSpawn;
            }
        }
    }
    
    private void InstantiateHexGameObjects()
    {
        foreach (var kvp in hexGrid)
        {
            var coord = kvp.Key;
            var hexData = kvp.Value;
            
            Vector3 worldPos = HexToWorldPosition(coord);
            GameObject prefabToUse = GetPrefabForHexType(hexData.type);
            
            GameObject hexGO = Instantiate(prefabToUse, worldPos, Quaternion.identity, hexParent);
            hexGO.name = $"Hex_{coord}_{hexData.type}";
            
            hexData.gameObject = hexGO;
            
            // Store hex data reference directly in the GameObject's name for now
            // You can create a HexTile component later if needed
        }
    }
    
    private GameObject GetPrefabForHexType(HexType type)
    {
        return type switch
        {
            HexType.CenterHub => centerHubPrefab ?? hexPrefab,
            HexType.Pathway => pathwayPrefab ?? hexPrefab,
            HexType.DefenderSpot => defenderSpotPrefab ?? hexPrefab,
            HexType.EdgeSpawn => edgeSpawnPrefab ?? hexPrefab,
            _ => hexPrefab
        };
    }
    
    private HexCoordinates FindClosestHexInDirection(HexCoordinates from, Vector3 worldDirection)
    {
        HexCoordinates bestHex = from;
        float bestDot = -1f;
        
        foreach (var direction in HEX_DIRECTIONS)
        {
            HexCoordinates candidate = new HexCoordinates(from.q + direction.q, from.r + direction.r);
            
            if (!hexGrid.ContainsKey(candidate)) continue;
            
            Vector3 candidateWorld = HexToWorldPosition(candidate);
            Vector3 fromWorld = HexToWorldPosition(from);
            Vector3 hexDirection = (candidateWorld - fromWorld).normalized;
            
            float dot = Vector3.Dot(hexDirection, worldDirection);
            if (dot > bestDot)
            {
                bestDot = dot;
                bestHex = candidate;
            }
        }
        
        return bestHex;
    }
    
    private List<HexCoordinates> GetAlternativeDirections(HexCoordinates from, Vector3 preferredDirection)
    {
        List<HexCoordinates> alternatives = new List<HexCoordinates>();
        
        foreach (var direction in HEX_DIRECTIONS)
        {
            HexCoordinates candidate = new HexCoordinates(from.q + direction.q, from.r + direction.r);
            
            if (!hexGrid.ContainsKey(candidate)) continue;
            
            Vector3 candidateWorld = HexToWorldPosition(candidate);
            Vector3 fromWorld = HexToWorldPosition(from);
            Vector3 hexDirection = (candidateWorld - fromWorld).normalized;
            
            // Only consider directions that are somewhat aligned (dot > 0.3)
            float dot = Vector3.Dot(hexDirection, preferredDirection);
            if (dot > 0.3f)
            {
                alternatives.Add(candidate);
            }
        }
        
        return alternatives;
    }
    
    #endregion
    
    private Vector3 HexToWorldPosition(HexCoordinates hex)
    {
        // For flat-top hexagons (as shown in image)
        float size = hexSize * (1f + hexSpacing);
        
        // Correct hexagonal grid positioning for flat-top orientation
        float x = size * (3f/2f * hex.q);
        float z = size * (SQRT_3/2f * hex.q + SQRT_3 * hex.r);
        
        return transform.position + new Vector3(x, 0, z);
    }
    
    private List<HexCoordinates> GetHexRing(HexCoordinates center, int radius)
    {
        List<HexCoordinates> results = new List<HexCoordinates>();
        
        if (radius == 0)
        {
            results.Add(center);
            return results;
        }
        
        // Start at the "right" corner of the ring and walk counter-clockwise
        HexCoordinates hex = new HexCoordinates(center.q + radius, center.r);
        
        // Six directions for hexagonal movement (axial coordinates)
        HexCoordinates[] directions = {
            new HexCoordinates(-1, 1),  // NW
            new HexCoordinates(-1, 0),  // W  
            new HexCoordinates(0, -1),  // SW
            new HexCoordinates(1, -1),  // SE
            new HexCoordinates(1, 0),   // E
            new HexCoordinates(0, 1)    // NE
        };
        
        for (int i = 0; i < 6; i++)
        {
            for (int j = 0; j < radius; j++)
            {
                results.Add(hex);
                hex = new HexCoordinates(hex.q + directions[i].q, hex.r + directions[i].r);
            }
        }
        
        return results;
    }
    
    private HexCoordinates CubeToHex(Vector3 cube)
    {
        return new HexCoordinates((int)cube.x, (int)cube.z);
    }
    
    private Vector3 CubeRound(float x, float y, float z)
    {
        int rx = Mathf.RoundToInt(x);
        int ry = Mathf.RoundToInt(y);
        int rz = Mathf.RoundToInt(z);
        
        float x_diff = Mathf.Abs(rx - x);
        float y_diff = Mathf.Abs(ry - y);
        float z_diff = Mathf.Abs(rz - z);
        
        if (x_diff > y_diff && x_diff > z_diff)
            rx = -ry - rz;
        else if (y_diff > z_diff)
            ry = -rx - rz;
        else
            rz = -rx - ry;
        
        return new Vector3(rx, ry, rz);
    }
    

    
    #region Gizmos
    
    private void OnDrawGizmos()
    {
        if (!showGizmos) return;
        
        // Show hex grid both in play mode and edit mode after generation
        if (hexGrid.Count > 0)
        {
            // Draw lane connections first (behind hexes)
            if (showLaneConnections && showPathways)
                DrawLaneConnections();
            
            // Draw existing hexes with type-based colors and visibility
            foreach (var kvp in hexGrid)
            {
                var coord = kvp.Key;
                var hexData = kvp.Value;
                
                // Check visibility for this hex type
                if (!ShouldShowHexType(hexData.type, hexData.laneId)) continue;
                
                Vector3 pos = HexToWorldPosition(coord);
                
                // Get enhanced color for hex type - ensure solid color
                Color hexColor = GetEnhancedColorForHexType(hexData.type, hexData.laneId);
                hexColor.a = gizmoAlpha;
                Gizmos.color = hexColor;
                
                // Draw hex with special styling based on type
                DrawEnhancedHexGizmo(pos, hexSize, hexData.type, hexData.laneId);
                
                // Draw type labels
                if (showTypeLabels)
                {
                    #if UNITY_EDITOR
                    string label = GetHexTypeLabel(hexData.type, hexData.laneId);
                    if (showCoordinates)
                        label += $"\n{hexData.coordinates}";
                    UnityEditor.Handles.Label(pos + Vector3.up * 0.2f, label);
                    #endif
                }
            }
        }
        else
        {
            // Preview mode in editor - show basic grid with rainbow effect
            for (int ring = 0; ring <= gridRadius; ring++)
            {
                List<HexCoordinates> ringCoords = GetHexRing(HexCoordinates.Zero, ring);
                
                foreach (var coord in ringCoords)
                {
                    Vector3 pos = HexToWorldPosition(coord);
                    
                    // Rainbow preview effect
                    float hue = (ring * 0.15f + Vector3.Angle(pos, Vector3.right) / 360f) % 1f;
                    Color previewColor = Color.HSVToRGB(hue, 0.6f, 0.9f);
                    previewColor.a = gizmoAlpha;
                    
                    if (coord == HexCoordinates.Zero)
                        previewColor = Color.white;
                    
                    Gizmos.color = previewColor;
                    DrawEnhancedHexGizmo(pos, hexSize, HexType.Environment, -1);
                }
            }
        }
    }
    
    private bool ShouldShowHexType(HexType type, int laneId)
    {
        // Check lane-specific visibility
        if (showOnlyLane >= 0 && type == HexType.Pathway && laneId != showOnlyLane)
            return false;
        
        // Check type-specific visibility
        return type switch
        {
            HexType.CenterHub => showCenterHub,
            HexType.Pathway => showPathways,
            HexType.DefenderSpot => showDefenderSpots,
            HexType.EdgeSpawn => showEdgeSpawns,
            HexType.Environment => showEnvironment,
            _ => true
        };
    }
    
    private void DrawLaneConnections()
    {
        for (int laneIndex = 0; laneIndex < generatedLanes.Count; laneIndex++)
        {
            var lane = generatedLanes[laneIndex];
            if (lane.Count < 2) continue;
            
            // Skip if only showing specific lane and this isn't it
            if (showOnlyLane >= 0 && laneIndex != showOnlyLane) continue;
            
            // Get lane color
            Color connectionColor = laneIndex < laneConfigurations.Count ? 
                                  laneConfigurations[laneIndex].laneColor : Color.yellow;
            connectionColor.a = 0.5f;
            Gizmos.color = connectionColor;
            
            // Draw connections between lane hexes
            for (int i = 0; i < lane.Count - 1; i++)
            {
                Vector3 from = HexToWorldPosition(lane[i]) + Vector3.up * 0.1f;
                Vector3 to = HexToWorldPosition(lane[i + 1]) + Vector3.up * 0.1f;
                
                // Draw thick line
                DrawThickLine(from, to, 0.1f);
                
                // Draw arrow at end
                if (i == lane.Count - 2)
                {
                    Vector3 direction = (to - from).normalized;
                    DrawArrow(to, direction, 0.3f);
                }
            }
        }
    }
    
    private Color GetEnhancedColorForHexType(HexType type, int laneId = -1)
    {
        return type switch
        {
            HexType.CenterHub => centerHubColor,
            HexType.Pathway => GetLaneColor(laneId),
            HexType.DefenderSpot => defenderSpotColor,
            HexType.EdgeSpawn => edgeSpawnColor,
            _ => environmentColor
        };
    }
    
    private Color GetLaneColor(int laneId)
    {
        if (laneId >= 0 && laneId < laneConfigurations.Count)
        {
            return laneConfigurations[laneId].laneColor;
        }
        
        // Fallback rainbow colors for lanes without configuration
        float hue = (laneId * 0.618f) % 1f; // Golden ratio for even distribution
        return Color.HSVToRGB(hue, 0.8f, 1f);
    }
    
    private string GetHexTypeLabel(HexType type, int laneId)
    {
        return type switch
        {
            HexType.CenterHub => "🏠 HUB",
            HexType.Pathway => $"🛤️ L{laneId}",
            HexType.DefenderSpot => "🛡️ DEF",
            HexType.EdgeSpawn => "🚪 SPAWN",
            _ => "🌿 ENV"
        };
    }
    
    private void DrawEnhancedHexGizmo(Vector3 center, float size, HexType type, int laneId)
    {
        Vector3[] corners = new Vector3[6];
        for (int i = 0; i < 6; i++)
        {
            float angle = 60f * i * Mathf.Deg2Rad;
            corners[i] = center + new Vector3(
                size * Mathf.Cos(angle),
                0,
                size * Mathf.Sin(angle)
            );
        }
        
        // Set solid color for this hex - no gradients
        Color solidColor = GetEnhancedColorForHexType(type, laneId);
        solidColor.a = gizmoAlpha;
        Gizmos.color = solidColor;
        
        // Draw based on type and settings
        if (showFilledGizmos)
        {
            // Draw filled hexagon with solid color
            DrawSolidFilledHex(corners, center, solidColor);
        }
        
        // Always draw outline with type-specific styling
        DrawHexOutline(corners, type, solidColor);
        
        // Draw special markers based on type
        DrawTypeSpecificMarkers(center, size, type, laneId, solidColor);
    }
    
    private void DrawSolidFilledHex(Vector3[] corners, Vector3 center, Color solidColor)
    {
        // Ensure solid color throughout
        Gizmos.color = solidColor;
        
        // Draw filled hexagon using Unity's mesh drawing for solid color
        #if UNITY_EDITOR
        UnityEditor.Handles.color = solidColor;
        
        // Draw filled polygon using Handles for better solid fill
        Vector3[] vertices = new Vector3[corners.Length];
        for (int i = 0; i < corners.Length; i++)
        {
            vertices[i] = corners[i];
        }
        UnityEditor.Handles.DrawAAConvexPolygon(vertices);
        #else
        // Fallback for runtime - draw triangular segments
        for (int i = 0; i < 6; i++)
        {
            Gizmos.color = solidColor;
            Vector3[] triangle = {
                center,
                corners[i],
                corners[(i + 1) % 6]
            };
            
            Gizmos.DrawLine(triangle[0], triangle[1]);
            Gizmos.DrawLine(triangle[1], triangle[2]);
            Gizmos.DrawLine(triangle[2], triangle[0]);
        }
        #endif
    }
    
    private void DrawHexOutline(Vector3[] corners, HexType type, Color solidColor)
    {
        // Ensure solid color for outline
        Gizmos.color = solidColor;
        
        float lineThickness = type switch
        {
            HexType.CenterHub => 0.15f,
            HexType.Pathway => 0.12f,
            HexType.DefenderSpot => 0.1f,
            HexType.EdgeSpawn => 0.08f,
            _ => 0.05f
        };
        
        // Draw hexagon outline with varying thickness
        for (int i = 0; i < 6; i++)
        {
            Vector3 from = corners[i];
            Vector3 to = corners[(i + 1) % 6];
            
            if (type == HexType.CenterHub || type == HexType.Pathway)
            {
                DrawThickLine(from, to, lineThickness, solidColor);
            }
            else
            {
                Gizmos.color = solidColor;
                Gizmos.DrawLine(from, to);
            }
        }
    }
    
    private void DrawTypeSpecificMarkers(Vector3 center, float size, HexType type, int laneId, Color solidColor)
    {
        // Ensure markers use the same solid color
        Gizmos.color = solidColor;
        
        switch (type)
        {
            case HexType.CenterHub:
                // Draw pulsing center sphere
                float pulseSize = size * 0.3f * (1f + 0.2f * Mathf.Sin(Time.time * 3f));
                Gizmos.DrawWireSphere(center + Vector3.up * 0.1f, pulseSize);
                break;
                
            case HexType.Pathway:
                // Draw direction arrow if part of a lane
                if (laneId >= 0 && laneId < generatedLanes.Count)
                {
                    var lane = generatedLanes[laneId];
                    var currentIndex = lane.FindIndex(coord => coord == WorldToHex(center));
                    if (currentIndex >= 0 && currentIndex < lane.Count - 1)
                    {
                        Vector3 nextPos = HexToWorldPosition(lane[currentIndex + 1]);
                        Vector3 direction = (nextPos - center).normalized;
                        DrawArrow(center + Vector3.up * 0.05f, direction, size * 0.4f, solidColor);
                    }
                }
                break;
                
            case HexType.DefenderSpot:
                // Draw shield symbol
                DrawShieldSymbol(center, size * 0.4f, solidColor);
                break;
                
            case HexType.EdgeSpawn:
                // Draw spawn portal effect
                DrawSpawnPortal(center, size * 0.3f, solidColor);
                break;
        }
    }
    
    private void DrawThickLine(Vector3 from, Vector3 to, float thickness, Color color = default)
    {
        if (color != default(Color))
            Gizmos.color = color;
            
        Vector3 direction = (to - from).normalized;
        Vector3 perpendicular = Vector3.Cross(direction, Vector3.up) * thickness * 0.5f;
        
        // Draw multiple lines to simulate thickness
        Gizmos.DrawLine(from + perpendicular, to + perpendicular);
        Gizmos.DrawLine(from - perpendicular, to - perpendicular);
        Gizmos.DrawLine(from, to); // Center line
    }
    
    private void DrawArrow(Vector3 position, Vector3 direction, float size, Color color = default)
    {
        if (color != default(Color))
            Gizmos.color = color;
            
        Vector3 right = Vector3.Cross(direction, Vector3.up) * size * 0.3f;
        Vector3 arrowHead = position + direction * size;
        Vector3 arrowLeft = position + direction * size * 0.7f - right;
        Vector3 arrowRight = position + direction * size * 0.7f + right;
        
        Gizmos.DrawLine(position, arrowHead);
        Gizmos.DrawLine(arrowHead, arrowLeft);
        Gizmos.DrawLine(arrowHead, arrowRight);
    }
    
    private void DrawShieldSymbol(Vector3 center, float size, Color color = default)
    {
        if (color != default(Color))
            Gizmos.color = color;
            
        // Draw a simple shield shape
        Vector3 top = center + Vector3.forward * size + Vector3.up * 0.05f;
        Vector3 bottom = center - Vector3.forward * size + Vector3.up * 0.05f;
        Vector3 left = center - Vector3.right * size * 0.7f + Vector3.up * 0.05f;
        Vector3 right = center + Vector3.right * size * 0.7f + Vector3.up * 0.05f;
        
        Gizmos.DrawLine(top, left);
        Gizmos.DrawLine(left, bottom);
        Gizmos.DrawLine(bottom, right);
        Gizmos.DrawLine(right, top);
        Gizmos.DrawLine(left, right); // Cross
        Gizmos.DrawLine(top, bottom); // Cross
    }
    
    private void DrawSpawnPortal(Vector3 center, float size, Color color = default)
    {
        if (color != default(Color))
            Gizmos.color = color;
            
        // Draw rotating portal rings
        float time = Time.time * 2f;
        int rings = 3;
        
        for (int ring = 0; ring < rings; ring++)
        {
            float ringSize = size * (0.5f + ring * 0.3f);
            float rotation = time + ring * 120f;
            
            for (int i = 0; i < 8; i++)
            {
                float angle1 = (rotation + i * 45f) * Mathf.Deg2Rad;
                float angle2 = (rotation + (i + 1) * 45f) * Mathf.Deg2Rad;
                
                Vector3 point1 = center + new Vector3(
                    Mathf.Cos(angle1) * ringSize,
                    0.1f,
                    Mathf.Sin(angle1) * ringSize
                );
                Vector3 point2 = center + new Vector3(
                    Mathf.Cos(angle2) * ringSize,
                    0.1f,
                    Mathf.Sin(angle2) * ringSize
                );
                
                Gizmos.DrawLine(point1, point2);
            }
        }
    }
    
    #endregion
}
